begin
Insert into PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORYID, UNITPRICE, LASTUPDATE) Values (3, 'Product3', 100, 100000,NULL);
Insert into PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORYID, UNITPRICE, LASTUPDATE) Values (1, 'Product1', 1, 1000,NULL);
Insert into PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORYID, UNITPRICE, LASTUPDATE) Values (2, 'Product2', 50, 25000,NULL);
Insert into PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORYID, UNITPRICE, LASTUPDATE) Values (4, 'Product4', 3, 55,NULL);
Insert into PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORYID, UNITPRICE, LASTUPDATE) Values (5, 'Product5', 3, 15,NULL);
COMMIT;
end;
