
CREATE TABLE CUSTOMERS
(
  CUSTOMERID    VARCHAR2(5 BYTE)                NOT NULL,
  COMPANYNAME   VARCHAR2(40 BYTE)               NOT NULL,
  CONTACTNAME   VARCHAR2(30 BYTE),
  CONTACTTITLE  VARCHAR2(30 BYTE),
  ADDRESS       VARCHAR2(60 BYTE),
  CITY          VARCHAR2(15 BYTE),
  REGION        VARCHAR2(15 BYTE),
  POSTALCODE    VARCHAR2(10 BYTE),
  COUNTRY       VARCHAR2(15 BYTE),
  PHONE         VARCHAR2(24 BYTE),
  FAX           VARCHAR2(24 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PK_CUSTOMERID ON CUSTOMERS
(CUSTOMERID)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE CUSTOMERS ADD (
  CONSTRAINT PK_CUSTOMERID
 PRIMARY KEY
 (CUSTOMERID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


