
CREATE TABLE PRODUCTS
(
  PRODUCTID    INTEGER,
  PRODUCTNAME  VARCHAR2(50 BYTE),
  CATEGORYID   INTEGER,
  UNITPRICE    INTEGER                          NOT NULL,
  LASTUPDATE   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PRODUCTS_KEY ON PRODUCTS
(PRODUCTID)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PRODUCTS ADD (
  CONSTRAINT PRODUCTS_KEY
 PRIMARY KEY
 (PRODUCTID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


