IF EXISTS (SELECT * FROM sysdatabases WHERE NAME = 'Northwind')
BEGIN
	ALTER DATABASE Northwind
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE;
	
	DROP DATABASE Northwind
END

GO

IF SUSER_ID ('entlib') IS NOT NULL
BEGIN
	DROP LOGIN entlib
END