CREATE OR REPLACE PROCEDURE "GETCUSTOMERBYID" ( vCustomerId IN Customers.CustomerID%TYPE := 1, cur_OUT OUT PKGENTLIB_ARCHITECTURE.CURENTLIB_ARCHITECTURE)
	AS

BEGIN
    OPEN cur_OUT FOR
	SELECT *
	FROM Customers where customerID = vCustomerId;
END;
/

