CREATE OR REPLACE PROCEDURE "GETCUSTOMERSVIEW" ( cur_OUT OUT PKGENTLIB_ARCHITECTURE.CURENTLIB_ARCHITECTURE)
	AS

BEGIN
    OPEN cur_OUT FOR
	SELECT *
	FROM Customers WHERE CustomerId in ('BLAUS','BLONP','BOLID')
	ORDER BY CustomerID;
END;
/
