CREATE OR REPLACE PROCEDURE "GETCUSTOMERSANDPRODUCTSVIEW" (cur_OUT OUT PKGENTLIB_ARCHITECTURE.CURENTLIB_ARCHITECTURE,cur_Products OUT PKGENTLIB_ARCHITECTURE.CURENTLIB_ARCHITECTURE)
	AS

BEGIN
    OPEN cur_OUT FOR
	SELECT *
	FROM Customers where CustomerID in ('BLAUS','BLONP','BOLID') 
	ORDER BY CustomerID;
	OPEN cur_Products FOR
	SELECT *
	FROM Products where ProductID in (1,2,3,4,5) order by ProductID;

END;
/

