CREATE OR REPLACE PROCEDURE UPDATEEMPLOYEES(
	vEMPLOYEEID IN EMPLOYEES.EMPLOYEEID%TYPE,
	vFIRSTNAME IN EMPLOYEES.FIRSTNAME%TYPE,
	vLASTNAME IN EMPLOYEES.LASTNAME%TYPE,
	vAGE IN EMPLOYEES.AGE%TYPE
)
AS
BEGIN
	 UPDATE EMPLOYEES SET
			FIRSTNAME = vFIRSTNAME,
			LASTNAME  = vLASTNAME,
			AGE		  = vAGE
	WHERE
		EMPLOYEEID	  = vEMPLOYEEID;
END;
/

